### [1] 게시글 등록 1
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "안녕하세요",
  "content": "구보윤입니다"
}

### [2] 게시글 등록 2
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "",
  "content": ""
}

### [3] 게시글 전체 조회
GET http://localhost:8080/posts

### [4] 게시글 수정
PUT http://localhost:8080/posts/1
Content-Type: application/json

{
  "title": "안녕히가세요",
  "content": "수정완료."
}

### [5] 게시글 수정 후 조회
GET http://localhost:8080/posts/1

### [6] 게시글 삭제
DELETE http://localhost:8080/posts/2

### [7] 게시글 삭제 후 조회
GET http://localhost:8080/posts/2

### 등록
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "안녕하세요",
  "content": "안녕히가세요."
}